[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clase-django-orm"
version = "0.1.0"
description = "Django ORM project"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "Django==6.0.3",
    "gunicorn==21.2.0",
    "python-dotenv==1.0.0",
    "whitenoise==6.6.0",
]

[tool.uv]
dev-dependencies = []

[tool.setuptools]
packages = ["config", "clientes"]
